#!/bin/bash
#PBS -l nodes=1:ppn=8,vmem=16g,walltime=18:00:00
#PBS -N segroifrompair
#PBS -V

set -e

echo "running bsc_SegROIfromPairStringList_BL"
time singularity exec -e docker://brainlife/mcr:neurodebian1604-r2017a ./compiled/bsc_SegROIfromPairStringList_BL

echo "generating tracts/"
#TODO for Dan

echo "generating surfaces/"
atlas=$(jq -r .atlas config.json)
time singularity exec -e docker://brainlife/pythonvtk:1.1 ./freesurfer2vtks.py $atlas/parc.nii.gz
