#!/bin/bash
#PBS -l nodes=1:ppn=8,vmem=16g,walltime=18:00:00
#PBS -N roitracking
#PBS -V

set -e

time singularity exec -e docker://brainlife/mcr:neurodebian1604-r2017a ./compiled/bsc_SegROIfromPairStringList_BL

